---
title: ""
output: 
  html_document
---

<br><br><br><br><br/>




### Prey Species results notes:

<br><br/>

#### see model selection info under species tabs

<br/>

- N mixture model by species to get relative site abundance  
- evaluated covs days since lure, julian date, and julian date sq, on detection
- best model by waic (with significant covs) will be used to provide N (site abundance)
- Using mean(N) for site abundance, which is a decimal value, does not represent 
- actual N at the site, but relative abundance compared to the other sites
- prey site abundace will be used a cov in the predator occ models to evaluate predator prey correlation

<br><br/>

#### model output notes:

<br/>

- some things of interest in the output
-- detection table include N values by year from the dot model
-- I think these represent an estimate of home ranges that intersect with camera stations
-- and not a total N value for the entire study area
- parameters:
-- alphas: detection covs
-- lamdas: poisson rate on N
-- p  detection rate (in the dot model)
- Parameter relationships:
-- backtransformed alpha relationship to detection rate
- for instance julian date + julian date sq for WTJackrabbit peaks in the early spring monthes
- x axis is centered and scaled -- why the vals are between - 2 and 2

